package io.crossplane.compositefunctions.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.security.Security;

@SpringBootApplication
public class ExampleFunctionApplication {

    public static void main(String[] args) {
        // The bouncycastle provider is needed for the autogenerated certificates that crossplane generates to work
        Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider());
        SpringApplication.run(ExampleFunctionApplication.class, args);

    }
}
